### ISSUE TITLE
Install ruby using RPM?

### ISSUE THREAD

**Issue by simaishi** [ManageIQ/manageiq-appliance-build#393]
Opening this issue to discuss if we should switch to using CentOS AppStream ruby, rather than using `ruby-install`

Pros for switching to AppStream:
- Less build time: `ruby-install` downloads and compiles ruby on every build, and this takes about 4-6 minutes. If we use ruby RPM, that will be a part of package installation and not a separate process.
- Reliability: One of the reasons appliance won't start up is ruby not being properly installed. This doesn't happen too often, but it does happen. When it happens, it's usually network related. There will be one less place we need to rely on network being stable
- Maintenance: we will need to pick which minor version (e.g. 2.5) to use, but all updates/patches will come from CentOS and the latest released one will be automatically picked up during build. With `ruby-install`, we need to make a change for every version update (e.g. 2.5.5 -> 2.5.6). Also, users can run `yum update` to update ruby on existing appliances.

Cons for AppStream:
- If we want to use the latest ruby, that might not be available in AppStream yet. For example, 2.7 isn't currently available.
- Ruby is packaged differently in RPM and this results in different behavior in bundle. One difference, which causes some %post commands to fail, is: some "default" gems (e.g. json, psych)  are installed but not marked as "default", and `bundle clean --force` removes those gems.
- Security fixes might take longer to be released

Looking into bundle behavior and switching to AppStream is something we should do?  Not sure if setting a path would be an option for upstream. Even if that works, would that be confusing to users?

@jrafanie @NickLaMuro @Fryguy @bdunne  - since you helped me with downstream ruby/bundle issues before... hoping to get some help!

**Comment by NickLaMuro** [comment]
So on the surface, I would say that the con of not having the "latest and greatest" Ruby isn't too big of a deal, and us probably upgrading Rails and being on top of that is a bigger hurdle (that doesn't involve the build at all) that we need to overcome.  I say this since I was getting some Ruby deprecation warnings when trying to use 2.7 with Rails 6, so I think we are pretty good if we are a patch release behind Ruby for now.

That said, the other con you brought up seems much more concerning since it might break at lot of assumptions we have made on the appliance.  That said, it might be a good motivator to potentially fix those areas of our application where we are too reliant on the appliance environment for things to work.

I would add one Con to the list, though, and that is that if there is ever a security vulnerability with Ruby itself, we will be at the mercy of AppStream to get the fix applied, or have to resort to falling back to the `ruby-install` way of doing things until it is patched there.  I think maintaining two workflows for installing Ruby is probably a recipe for migraines, so I would hope that the security team for AppStream is on their game (FYI:  I am unfamiliar with AppStream in general).

**Comment by simaishi** [comment]
Thanks @NickLaMuro 

Added the security fix concern to the "Cons" list. I'm also checking more on the "default" gems difference in AppStream ruby.

**Comment by bdunne** [comment]
- Is there any timeline for how quickly AppStream will build the latest rubies? I remember software collections being way behind.
- I know we have required a minimum patch version in the past due to bugs in lower patch versions.  Is there any way to specify that?
- Does AppStream work properly with `Bundle.with_clean_env`?

**Comment by jrafanie** [comment]
> * Ruby is packaged differently in RPM and this results in different behavior in bundle. One difference, which causes some %post commands to fail, is: some "default" gems (e.g. json, psych)  are installed but not marked as "default", and `bundle clean --force` removes those gems.

Yeah, that's the major concern.  What do they change with regard to stdlib but also how binary extensions get installed into various locations?  If people are expected to be able to do bundle operations like clean on upstream appliances, that's a definite problem.

**Comment by Fryguy** [comment]
If it's anything like SCL, I'm a huge :-1: .  The changes that SCL did to Ruby made dealing with it a huge headache.  Maybe those are just battle scars though and AppStream is different.

---

Another idea... What if we did a ruby-install on-demand on a build machine and then packaged that in some form (RPM in copr?).  Then, you can avoid the build timing problems, but we also keep the flexibility to control the Ruby version.  Or is that too difficult?

**Comment by simaishi** [comment]
Thank you for the feedback!

I was hoping to avoid building our own RPM, only because that seemed a wrong approach when RHEL/CentOS is providing it without need of extra steps (e.g. enabling it before use, which was the case with SCL). But AppStream RPM behaves differently and making appliance work with it seems to be a lot more work with more unknowns, so looked into building our own. The main goal is to avoid compiling ruby on every build.

Built RPM without using any ruby installer like `ruby-install`, but running `make` using ruby source. Appliance build using RPM was successful, psych/json stayed on the machine and manageiq app started. 

The issue about irb being removed (https://github.com/ManageIQ/manageiq-appliance-build/issues/408) exists with RPM as well. Will have to take a look at bundler a bit more.

**Comment by simaishi** [comment]
Resolved by https://github.com/ManageIQ/manageiq-appliance-build/pull/415. Switching to RPM based appliance build changed gem install dir as well as need to run `bundle clean`, so we're now using ruby RPM from AppStream.

If not having the latest version or not having a security patch in a timely manner become a problem, we can look into building our own ruby package.
