### ISSUE TITLE
Move ansible python module installation from post script to a standalone rpm

### ISSUE THREAD

**Issue by simaishi** [ManageIQ/manageiq-appliance-build#423]
Since python module versions for ansible venv are hardcoded in [post script](https://github.com/ManageIQ/manageiq-appliance-build/blob/master/kickstarts/partials/post/python_modules.ks.erb), we should move this to a standalone RPM to avoid going through install process on every build.

This will eliminate a need to install a few development packages too.

- [x] https://github.com/ManageIQ/manageiq-rpm_build/pull/102
- [x] https://github.com/ManageIQ/manageiq-rpm_build/pull/319
- [x] Remove from pods image (~~https://github.com/ManageIQ/manageiq-pods/pull/636~~ https://github.com/ManageIQ/manageiq-pods/pull/906)
- [x] Remove from appliance image (~~#443~~ #534)

**Comment by Fryguy** [comment]
can we somehow name it such that we know it's for embedded ansible?

**Comment by simaishi** [comment]
Based on comments in https://github.com/ManageIQ/manageiq-appliance-build/pull/392, I assume we do want to continue providing python modules, but with reduced module list?

I don't know exactly how/where those are used and how to determine which module is needed.  @Fryguy @carbonin can you help?

**Comment by simaishi** [comment]
@NickLaMuro wondering if you can help me figuring this out.

**Comment by NickLaMuro** [comment]
@simaishi sure, though I think I am going to have a counter opinion to what both @Fryguy and Carboni had.

Simply put, I think it is simpler for us to just copy what AWX/Tower does because I don't really want to get into the business of trying to figure out what to support and not support out of Ansible, and they have a dedicated team for that where we basically have... me.

That way, we can simply just point to the `ansible`/Tower documentation as a source of truth instead of trying to figure it out for ourselves.

For comments like this:

https://github.com/ManageIQ/manageiq-appliance-build/pull/392#discussion_r393285731

I honestly think "who cares", it is one module.  This isn't loaded unless it is needed, and unless it is conflicting with something else we have (which, since these are python modules and not other RPM packages, I don't think we are), I don't see the problem.

The alternative to trying comb through each module with every update and try and determine what is needed and not from us (and there doesn't seem to be a definitive source in upstream for this), instead of just doing a couple commands (aka:  `pip3 freeze -l`) and including everything.  It is slightly wasteful, but I think from a performance and RPM/appliance side perspective, I think it is almost negligible.

**Comment by simaishi** [comment]
@NickLaMuro Thank you. So I think we have 2 things to discuss and come to a conclusion.

1. What modules to include.  Same as AWX/Tower or only what we need?
1. When to update

There is no rpm upstream, which is why we're running pip install during appliance build. Regardless of what we decide for the first question, we also need to think about when to update. "ansible" rpm comes from upstream and will be kept up-to-date. There is a compatibility matrix for Tower/Ansible. So if we don't update our venv, that might not cover all modules needed with a newer version of Ansible.  But, that might not matter, if we only really care about handful of modules...

**Comment by NickLaMuro** [comment]
I assume my opinion was obvious one the above, but I figured I should still weigh in:

> 1. What modules to include. Same as AWX/Tower or only what we need?

As mentioned above, I am in the "Same as AWX/Tower".

> 2. When to update

I guess this one is maybe less obvious, but I would say no more than once a release, but probably I would shoot for once a year to stay up to date, and only earlier if asked.

However, I am just throwing out suggestions that I just came up with, so I don't have a strong opinion on this one.
